name: 'Configuration Manager'
type: module
description: 'Allows administrators to manage configuration changes.'
package: Core
# version: VERSION
# core: 8.x
configure: config.sync

# Information added by Drupal.org packaging script on 2014-08-16
version: '8.0.0-alpha14+98-dev'
core: '8.x'
project: 'drupal'
datestamp: 1408190839
